<?php
/**
 * | ---------------------------------------------------------------------------------------------------
 * | ProjectName: ticket
 * | ---------------------------------------------------------------------------------------------------
 * | Author：johnxu <fsyzxz@163.com>
 * | ---------------------------------------------------------------------------------------------------
 * | Home: https://www.xfjpeter.cn
 * | ---------------------------------------------------------------------------------------------------
 * | Data: 201905242019-05-24
 * | ---------------------------------------------------------------------------------------------------
 * | Desc:
 * | ---------------------------------------------------------------------------------------------------
 */

namespace app\api\controller;

use johnxu\tool\Str;

class Activity extends Api
{
    /**
     * @var \app\api\model\Activity
     */
    protected $model;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = model('activity');
    }

    // 活动列表
    public function index()
    {
        $list  = $this->model->page($this->page, $this->limit)->select();
        $total = $this->model->count('*');

        return json([
            'err_code' => 0,
            'message'  => 'success',
            'data'     => [
                'list'  => $list,
                'total' => $total,
            ],
        ]);
    }

    // 发布活动
    public function add()
    {
        $data       = $this->request->post();
        $data['no'] = Str::getInstance()->generateTradeNo();
        if (isset($data['time'])) {
            $data['start_time'] = isset($data['time'][0]) ? strtotime($data['time'][0]) : 0;
            $data['end_time']   = isset($data['time'][1]) ? strtotime($data['time'][1]) : 0;
            unset($data['time']);
        }

        // 查询hall_id
        $map         = model('hall')->where('id', $data['hall_id'])->value('map');
        $data['map'] = $map;

        $activity = $this->model::create($data);

        return $activity
            ? json(['err_code' => 0, 'message' => '发布成功', 'data' => $activity])
            : json(['err_code' => 1, 'message' => '发布失败']);
    }

    // 保存
    public function save(string $no = '')
    {
        $activity = $this->model->get(['no' => $no]);
        $data     = $this->request->post();
        if (isset($data['time'])) {
            $data['start_time'] = isset($data['time'][0]) ? strtotime($data['time'][0]) : 0;
            $data['end_time']   = isset($data['time'][1]) ? strtotime($data['time'][1]) : 0;
            unset($data['time']);
        }
        if ($activity) {
            return $activity->save($data)
                ? json(['err_code' => 0, 'message' => '保存成功', 'data' => $activity])
                : json(['err_code' => 1, 'message' => '保存失败']);
        } else {
            return json([
                'err_code' => 1,
                'message'  => '更新失败',
            ]);
        }
    }

    // 获取活动
    public function get(string $no = '')
    {
        $activity = $this->model->get(['no' => $no]);

        if (!$activity) {
            return json(['err_code' => 1, 'message' => '没有找到该活动']);
        }

        return json(['err_code' => 0, 'message' => 'success', 'data' => $activity]);
    }

    // 删除活动
    public function delete(string $no = '')
    {
        $activity = $this->model->get(['no' => $no]);
        if ($activity->status) {
            return json([
                'err_code' => 1,
                'message'  => '活动处于开启状态不能删除，请先关闭活动',
            ]);
        } else {
            // 删除该活动的订单
            model('order')->whereLike('details', "%{$activity->no}%")->delete();

            return $activity->delete()
                ? json(['err_code' => 0, 'message' => 'success'])
                : json(['err_code' => 1, 'message' => '删除活动失败']);
        }
    }

    // 更新座位
    public function updateSeat()
    {
        $no       = $this->request->post('no');
        $activity = $this->model->get(['no' => $no]);
        if (!$activity) {
            return json([
                'err_code' => 1,
                'message'  => '活动不存在',
            ]);
        }

        // 查询座位图
        $hall = model('hall')->get($activity->hall_id);
        if (!$hall || $hall->status != 1) {
            return json([
                'err_code' => 1,
                'message'  => '座位图不存在或未开启',
            ]);
        }

        $maps = $hall->map;
        foreach ($activity->map as $akey => $amap) {
            foreach ($amap as $key => $map) {
                if (!isset($maps[$akey][$key]) && $map->type == '@') {
                    return json([
                        'err_code' => 1,
                        'message'  => '有座位已经被购买，更新的座位却没有该座位',
                    ]);
                } else {
                    $maps[$akey][$key] = [
                        'no'   => $map->no,
                        'type' => $map->type,
                    ];
                }
            }
        }

        $activity->map = $maps;
        $activity->save();

        return json([
            'err_code' => 0,
            'message'  => '更新座位成功',
        ]);
    }
}