<?php
/**
 * | ---------------------------------------------------------------------------------------------------
 * | ProjectName: ticket
 * | ---------------------------------------------------------------------------------------------------
 * | Author：johnxu <fsyzxz@163.com>
 * | ---------------------------------------------------------------------------------------------------
 * | Home: https://www.xfjpeter.cn
 * | ---------------------------------------------------------------------------------------------------
 * | Data: 201905252019-05-25
 * | ---------------------------------------------------------------------------------------------------
 * | Desc:
 * | ---------------------------------------------------------------------------------------------------
 */

namespace app\api\controller;

class Hall extends Api
{
    /**
     * @var \app\api\model\Hall
     */
    protected $model;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = model('hall');
    }

    // 列表
    public function index()
    {
        $type = $this->request->param('type', '');
        if ($type) {
            $list = $this->model->where('status', 1)->select();
        } else {
            $list = $this->model->select();
        }

        return json([
            'err_code' => 0,
            'message'  => 'success',
            'data'     => [
                'list'  => $list,
                'total' => 0,
            ],
        ]);
    }

    // 获取指定
    public function get(int $id = 0)
    {
        $hall = $this->model->get($id);
        if (!$hall) {
            return json([
                'err_code' => 1,
                'message'  => '异常操作',
            ]);
        }

        return json([
            'err_code' => 0,
            'message'  => 'success',
            'data'     => $hall,
        ]);
    }

    // 保存
    public function save(int $id = 0)
    {
        $data        = $this->request->post();
        $data['map'] = $this->map($data['map']);
        $hall        = $this->model->get(['id' => $id]);
        if (!$hall) {
            return json([
                'err_code' => 1,
                'message'  => '操作异常',
            ]);
        }

        return $hall->save($data)
            ? json(['err_code' => 0, 'message' => '保存成功', 'data' => $data])
            : json(['err_code' => 1, 'message' => '保存失败']);
    }

    // 添加厅
    public function add()
    {
        $data        = $this->request->post();
        $data['map'] = $this->map($data['map']);
        $hall        = $this->model::create($data);
        if ($hall) {
            return json([
                'err_code' => 0,
                'message'  => 'success',
                'data'     => $hall,
            ]);
        }

        return json([
            'err_code' => 1,
            'message'  => '添加失败',
        ]);
    }

    // 删除
    public function delete(int $id = 0)
    {
        return $this->model::destroy(['id' => $id])
            ? json([
                'err_code' => 0,
                'message'  => '删除成功',
            ])
            : json([
                'err_code' => 1,
                'message'  => '删除失败',
            ]);
    }

    protected function map($data)
    {
        foreach ($data as &$map) {
            foreach ($map as &$item) {
                if (isset($item['no'])) {
                    $item['type'] = $item['no'];
                } else {
                    $item = [
                        'no'   => $item,
                        'type' => $item,
                    ];
                }
            }
        }

        return $data;
    }
}