<?php
/**
 * | ---------------------------------------------------------------------------------------------------
 * | ProjectName: ticket
 * | ---------------------------------------------------------------------------------------------------
 * | Author：johnxu <fsyzxz@163.com>
 * | ---------------------------------------------------------------------------------------------------
 * | Home: https://www.xfjpeter.cn
 * | ---------------------------------------------------------------------------------------------------
 * | Data: 201905282019-05-28
 * | ---------------------------------------------------------------------------------------------------
 * | Desc:
 * | ---------------------------------------------------------------------------------------------------
 */

namespace app\api\controller;

class Order extends Api
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = model('order');
    }

    public function index()
    {
        $list  = $this->model->page($this->page, $this->limit)->order('create_time desc')->select();
        $total = $this->model->count('*');

        return json([
            'err_code' => 0,
            'message'  => 'success',
            'data'     => [
                'list'  => $list,
                'total' => $total,
            ],
        ]);
    }

    public function get(string $order_no = '')
    {
        $order = $this->model->get(['order_id' => $order_no]);

        if (!$order) {
            return json([
                'err_code' => 1,
                'message'  => '订单不存在',
            ]);
        }

        return json([
            'err_code' => 0,
            'message'  => 'success',
            'data'     => $order,
        ]);
    }
}