<?php
/**
 * | ---------------------------------------------------------------------------------------------------
 * | ProjectName: ticket
 * | ---------------------------------------------------------------------------------------------------
 * | Author：johnxu <fsyzxz@163.com>
 * | ---------------------------------------------------------------------------------------------------
 * | Home: https://www.xfjpeter.cn
 * | ---------------------------------------------------------------------------------------------------
 * | Data: 201905242019-05-24
 * | ---------------------------------------------------------------------------------------------------
 * | Desc:
 * | ---------------------------------------------------------------------------------------------------
 */

namespace app\api\controller;

class Rule extends Api
{
    /**
     * @var \app\api\model\Rule
     */
    protected $model;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = model('Rule');
    }

    // 获取规则
    public function index()
    {
        $list = $this->model->select();

        // $total = $this->model->count('*');

        return json([
            'err_code' => 0,
            'message'  => 'success',
            'data'     => [
                'list'  => \app\api\libs\Tree::getTreeRule($list->toArray()),
                'total' => 0,
            ],
        ]);
    }

    // 添加规则
    public function add()
    {
        $data = $this->request->post();
        $rule = $this->model::create($data);

        return $rule
            ? json(['err_code' => 0, 'message' => 'success', 'data' => $rule])
            : json(['err_code' => 1, 'message' => 'Add rule fail']);
    }

    // 获取指定规则
    public function get(int $id = 0)
    {
        $rule = $this->model->get(['id' => $id]);
        if (!$rule) {
            return json([
                'err_code' => 1,
                'message'  => 'Not found rule',
            ]);
        }

        return json([
            'err_code' => 0,
            'message'  => 'success',
            'data'     => $rule,
        ]);
    }

    // 更新
    public function save(int $id = 0)
    {
        $data = $this->request->post();
        $rule = $this->model->get(['id' => $id]);
        if (!$rule) {
            return json([
                'err_code' => 1,
                'message'  => 'Not found rule',
            ]);
        }

        return $rule->save($data)
            ? json(['err_code' => 0, 'message' => 'success', 'data' => $rule])
            : json(['err_code' => 1, 'message' => 'Update rule fail']);
    }

    // 删除规则
    public function delete(int $id = 0)
    {
        return $this->model->where('id', $id)->delete()
            ? json(['err_code' => 0, 'message' => 'success'])
            : json(['err_code' => 1, 'message' => 'Delete rule fail']);
    }
}